padre(enrique7,enrique8).
padre(enrique7,arturo).
padre(enrique7,margarita).
padre(enrique8,catalina).
padre(enrique8,ana).
padre(enrique8,juana).
padre(enrique8,maria).
padre(enrique8,isabel).
padre(enrique8,eduardo).
abuelo(enrique7,catalina).
abuelo(enrique7,maria).
abuelo(enrique7,ana).
abuelo(enrique7,isabel).
abuelo(enrique7,juana).
abuelo(enrique7,eduardo).
hermano(enrique8,arturo).
hermano(enrique,margarita).
hermano(arturo,margarita).
hermano(arturo,enrique8).
hermana(margarita,enrique8).
hermana(margarita,arturo).
hermana(catalina,maria).
hermana(catalina,ana).
hermana(catalina,isabel).
hermana(catalina,juana).
hermana(catalina,eduardo).
hermana(maria,catalina).
hermana(maria,ana).
hermana(maria,isabel).
hermana(maria,juana).
hermana(maria,eduardo).
hermana(ana,catalina).
hermana(ana,maria).
hermana(ana,isabel).
hermana(ana,juana).
hermana(ana,eduardo).
hermana(isabel,catalina).
hermana(isabel,maria).
hermana(isabel,ana).
hermana(isabel,juana).
hermana(isabel,eduardo).
hermana(juana,catalina).
hermana(juana,maria).
hermana(juana,ana).
hermana(juana,isabel).
hermana(juana,eduardo).
hermano(eduardo,juana).
hermano(eduardo,ana).
hermano(eduardo,isabel).
hermano(eduardo,catalina).
hermano(eduardo,maria).
hombre(enrique7).
hombre(enrique8).
hombre(arturo).
hombre(eduardo).
mujer(margarita).
mujer(catalina).
mujer(maria).
mujer(ana).
mujer(isabel).
mujer(juana).
